version: '3'
services:
  mysql_db:
    image: 'mysql:latest'
    container_name: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
      - './data_mysql:/var/lib/mysql'
      - ./init_db.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: shop
      MYSQL_USER: user
      MYSQL_PASSWORD: user1234  
    expose:
      - '3306'
  http_server:
    image: debian
    container_name: http_server
    restart: always
    volumes:
      - './AstralTest:/home/AstralTest'
    command: >
        bash -c "echo Start http server... && /home/AstralTest/AstralTest"    
  nginx:
    image: 'nginx:latest'
    container_name: nginx
    restart: always
    ports:
      - '80:80'
    depends_on:
      - http_server
    volumes:
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
      - './www:/var/www'      

volumes:
  data_mysql: null      